name: Resume test
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - main

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: ./README.md
          output_dir: .
      - uses: actions/upload-artifact@v1
        with:
          name: resume
          path: test